config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :projects do 
    resources :tasks 
  end 
  resources :user, :controller => "user"
  get "/projects/:project_id/tasks/:id/set_user/" => "tasks#set_user", :as => 'set_user' 
  get "/projects/:project_id/tasks/:id/complete/" => "tasks#complete", :as => 'complete'
  root to: 'projects#index' 

end

app/models/task.rb
class Task < ActiveRecord::Base
 has_ancestry
 belongs_to :project
 has_and_belongs_to_many :users

 validates :name, presence: true, length: 3..30
 validates :project, presence: true
 validates :end_at, presence: true
 validates :start_at, presence: true
 validate :end_at_cannot_be_less_then_started_at
 validate :compare_datetimes_with_project

 scope :not_completed, -> { where(completed: nil)}
 scope :find_completed, ->(project) { where(project: project,completed: true)} 

 private
 def compare_datetimes_with_project
  if parent.present?
    if end_at >= parent.end_at
       errors.add(:end_at, "can't end later than parent task")
    end
    if start_at <= parent.start_at
       errors.add(:start_at, "can't start earlier than parent task")
    end
  end
 end
 def end_at_cannot_be_less_then_started_at 
    return if end_at.blank? || created_at.blank?
    if end_at < created_at
      errors.add(:end_at, "can't end earlier than created")
    end
 end 
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :complete, :set_user]
  before_action :get_project
  before_action :get_users, only: [:edit, :new, :create, :update]
  #after_action :set_users, only: [:create, :update]
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.roots 
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @users = @task.users
    @descendants = @task.descendants.arrange_serializable
    respond_to do |format|
      format.html {}
      format.js {}
    end 
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @project.tasks.build(task_params)
    @task.users = []
    @task.parent = Task.find(params[:parent]) unless params[:parent].nil? 
    respond_to do |format|
      if @task.save
        format.html { redirect_to project_path(@project), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    params[:task][:users].delete("")
    params[:task][:users].each do |user|
      @task.users << User.where(id: user)
    end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
      @task.users = []
     # params[:task][:users].each do |user|
      #  @task.users << User.find(user) unless user.empty?
      #end   
    params[:task][:users].delete("")
    params[:task][:users].each do |user|
      @task.users << User.where(id: user)
    end
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to [@project, @task], notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_path(@project), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def complete
    @task.completed = true 
    @task.descendants.each{|descendants| descendants.update_attribute(:completed, true)}
    respond_to do |format|  
        if @task.save
          format.js
        else
          render :text => "Not success"
        end
    end
  end

  def set_user
    
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description,:start_at, :end_at)
    end

    def get_project
      @project = Project.find(params[:project_id])
    end 
    def get_users 
      @users = User.all
    end
    def set_users
      params[:task][:users].each do |user|
        @task.users << User.find(user) unless user.empty?
      end   
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def print_tasks (tasks)
    content_tag(:ul ) do
      tasks.each do |task|
        tag = content_tag(:li) do 
          concat link_to task['name'], project_task_path(@project, task['id'])
          concat print_tasks(task['children']) unless task['children'].length.zero?
        end
        concat tag
      end
    end
  end
end

app/views/tasks/_form.html.erb
<%= form_for [@project, @task], html: {class: "form"} do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="form-group">
    <%= f.label "Start Date", for: :start_at %>
    <%= f.datetime_select :start_at %>
  </div>
  <div class="form-group">
    <%= f.label "End Date", for: :end_at %>
    <%= f.datetime_select :end_at %>
  </div>
  <div class="form-group">
    <%= f.label "Select User" %>
    <%= f.select(:users, @users.collect { |u| [u.email, u.id]} , {:promt => "Please select"} , {:selected => f.object.users, :multiple => true, :size => 5 }) %>
  </div>
  <%= hidden_field_tag(:parent, params[:parent]) unless params[:parent].nil? %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<%= div_for task do %>
<% if task.completed.nil? %>
    <%= check_box_tag( "task_#{task.name.gsub(" ", "")}", task.id, false, class: "complete_check") %>
<% end %>
 <%= link_to task.name, [@project, task] %>
 <%= link_to "Show Subtasks", [@project, task], remote: true %>
<div class="subtasks" style="padding-left: 10px;">
</div>
<% end %>

app/views/tasks/complete.js.erb
$('#<%= dom_id(@task) %>').hide();
$('.completed').append("<%= escape_javascript(render @task) %>");

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', [@project, @task] %> |
<%= link_to 'Back', project_tasks_path(@project) %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= link_to 'Show', project_task_path( @project, task ) %></td>
        <td><%= link_to 'Edit', edit_project_task_path( @project, task ) %></td>
        <td><%= link_to 'Destroy', project_tasks_path( @project, task ), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_project_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', project_tasks_path %>

app/views/tasks/set_user.html.erb
<%= form_for set_user() do |f| %>
<% end %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>
<% if @descendants.present? %>
  <p>Subtasks</p>
  <%= print_tasks(@descendants) %>
<% end %> 
<% if @task.users %>
<p> Users: </p>
<% @task.users.each do |user| %>
<%= user.email %> <br>
<% end %>
<% end %>
<%= link_to 'Add subtask', new_project_task_path(@project,parent: @task) %> |
<%= link_to 'Edit', edit_project_task_path(@project, @task) %> |
<%= link_to 'Destroy',  project_task_path(@project, @task), method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', [@project]%>

app/views/tasks/show.js.erb
$('#<%= dom_id(@task) %> .subtasks').html("<%= escape_javascript(render @subtasks) %>");