config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :projects do 
    resources :tasks 
  end 
  resources :user, :controller => "user"
  get "/projects/:project_id/tasks/:id/set_user/" => "tasks#set_user", :as => 'set_user' 
  get "/projects/:project_id/tasks/:id/complete/" => "tasks#complete", :as => 'complete'
  root to: 'projects#index' 

end

app/models/project.rb
class Project < ActiveRecord::Base
 has_many :tasks, dependent: :destroy
 validates :name, presence: true, length: 6..30
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @tasks = @project.tasks.roots
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :end_at, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %><br>
    <%= f.label :description %><br>
    <%= f.text_area :description %><br>
     Select deadline:
    <%= f.datetime_select :end_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name of project</th>
      <th>Created</th>
      <th>Deadline</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project %></td>
        <td><%= project.created_at %></td>
        <td><%= project.end_at %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @project.name %>
</p>
<p>
  <strong>Description:</strong><br>
  <%= @project.description %>
</p>
  <%= render @tasks.not_completed%>

<div class="completed">
<% if Task.find_completed(@project).nil? %>
<% else %>
 Completed:
<%= render Task.find_completed(@project) %>
<% end %>
</div>
<script>
     $('.complete_check').change(function(){
        $.get('/projects/<%= @project.id %>/tasks/'+$(this).val()+'/complete/', function(data,status){
            if(status == 'success'){
              data
             }
        })
     })
   </script>
<div class="subtasks">
</div>
<div class="gantt">
</div>
    <script src="http://taitems.github.com/UX-Lab/core/js/prettify.js"></script>
  <script>
  $(function() {
            "use strict";
            $(".gantt").gantt({
source: [
<% @project.tasks.roots.each do |task| %>
   {
                    name: "<%= task.name %>",
                    desc: "",
                    values: [{
                        from: "/<%= task.start_at %>/",
                        to: "/<%= task.end_at %>/",
                        label: "<%= task.name %>",
                        customClass: "gantt<%= task.completed ? "Green" : "Red" %>"
                    
                    }]
                
                   },
   <% task.children.each do |children| %>
   {
                    name: "",
                    desc: "<%= children.name %>",
                    values: [{
                        from: "/<%= children.start_at %>/",
                        to: "/<%= children.end_at %>/",
                        label: "<%= children.name %>",
                        customClass: "gantt<%= children.completed ? "Green" : "Red" %>"
                    
                    }]
                
                   },

    <% end %> 
<% end %>                
                    ],
                navigate: "scroll",
                scale: "days",
                maxScale: "hours",
                itemsPerPage: 10,
          
onRender: function() {
              if (window.console && typeof console.log === "function") {
                        console.log("chart rendered");
                    
              }
                
          }
            
                });
            prettyPrint();
        
          });
  </script>
<%= link_to "Add Task", new_project_task_path(@project) %>
<br>
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>