config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :projects do 
    resources :tasks 
  end 
  resources :user, :controller => "user"
  get "/projects/:project_id/tasks/:id/set_user/" => "tasks#set_user", :as => 'set_user' 
  get "/projects/:project_id/tasks/:id/complete/" => "tasks#complete", :as => 'complete'
  root to: 'projects#index' 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 has_and_belongs_to_many :tasks
 validates :email, presence: true, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
 validates :password, presence: true, length: 6..16

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.where.not(id: current_user.id)
  end

  def new
    @user = User.new
  end

  def create 
    @user = User.new(params.require(:user).permit(:email, :password, :password_confirmation))
    
    if @user.save
      flash[:notice] = "Successfully created User." 
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated User."
      redirect_to root_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully deleted User."
      redirect_to root_path
    end
  end 
end

app/views/user/edit.html.erb
<h2>Add user</h2>

<%= form_for(@user, url: user_path, html: { class: "form-horizontal"}) do |f| %>
  <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-3 control-label" %>
     <%= f.email_field :email, class: "form_control", placeholder: "Email" %>
  </div>

  <div class="form-group">
    <%= f.label :password, class: "col-sm-3 control-label" %>
    <%= f.password_field :password, autocomplete: "off", class: "form_control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, class: "col-sm-3 control-label" %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off", class: "form_control"  %>
  </div>
    <%= f.submit "Add user", class: "btn btn-default" %>
<% end %>

app/views/user/index.html.erb
<h1>Users:</h1>
<table class="table">
<% @users.each do |user| %>
<tr>
  <td><%= user.email %></td>
  <td><%= link_to "Edit", edit_user_path(user) %></td>
</tr>
<% end %>
</table>
<%= link_to "Add User", controller: "/user", action: "new" %>

app/views/user/new.html.erb
<h2>Add user</h2>
<%= form_for(@user,url: user_index_path, html: { class: "form-horizontal"}) do |f| %>
  <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-3 control-label" %>
     <%= f.email_field :email, class: "form_control", placeholder: "Email" %>
  </div>

  <div class="form-group">
    <%= f.label :password, class: "col-sm-3 control-label" %>
    <%= f.password_field :password, autocomplete: "off", class: "form_control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, class: "col-sm-3 control-label" %>
    <%= f.password_field :password_confirmation, autocomplete: "off", class: "form_control"  %>
  </div>
    <%= f.submit "Add user", class: "btn btn-default" %>
<% end %>

app/views/user/show.html.erb
Login: <%= @user.login %>
<br>
Password: <%= @user.password %>